-- Operational data integrity hardening.
-- Rollback (manual): drop only the indexes/functions created here, reactivate
-- audited stock rows if necessary, and restore audit-recorded idempotency keys.
-- This migration never deletes rows or tables.

create table if not exists public.wms_migration_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  migration_name text not null,
  table_name text not null,
  record_id text not null,
  action text not null,
  previous_value jsonb not null default '{}'::jsonb,
  notes text not null default ''
);

alter table public.wms_migration_audit enable row level security;
revoke all on table public.wms_migration_audit from public, anon;
grant select, insert on table public.wms_migration_audit to authenticated;
drop policy if exists wms_migration_audit_admin on public.wms_migration_audit;
create policy wms_migration_audit_admin on public.wms_migration_audit
for all to authenticated
using (private.current_wms_is_global_admin())
with check (private.current_wms_is_global_admin());

update public.wms_replenishment_requests
set quantidade_pendente = greatest(0, coalesce(quantidade_solicitada, 0) - coalesce(quantidade_atendida, 0)),
    updated_at = now()
where quantidade_pendente is distinct from greatest(0, coalesce(quantidade_solicitada, 0) - coalesce(quantidade_atendida, 0));

-- Preserve the oldest idempotent request and neutralize only duplicate keys.
with ranked as (
  select id, warehouse_code, idempotency_key,
         row_number() over (partition by warehouse_code, idempotency_key order by created_at, id) as row_number
  from public.wms_replenishment_requests
  where idempotency_key is not null and idempotency_key <> ''
)
insert into public.wms_migration_audit (migration_name, table_name, record_id, action, previous_value, notes)
select '20260924014042_operational_data_integrity', 'wms_replenishment_requests', id, 'CLEAR_DUPLICATE_IDEMPOTENCY_KEY',
       jsonb_build_object('warehouse_code', warehouse_code, 'idempotency_key', idempotency_key),
       'Duplicate key retained on the oldest request; this row remains otherwise unchanged.'
from ranked
where row_number > 1
  and not exists (
    select 1 from public.wms_migration_audit audit
    where audit.migration_name = '20260924014042_operational_data_integrity'
      and audit.table_name = 'wms_replenishment_requests'
      and audit.record_id = ranked.id
      and audit.action = 'CLEAR_DUPLICATE_IDEMPOTENCY_KEY'
  );

with ranked as (
  select id,
         row_number() over (partition by warehouse_code, idempotency_key order by created_at, id) as row_number
  from public.wms_replenishment_requests
  where idempotency_key is not null and idempotency_key <> ''
)
update public.wms_replenishment_requests request
set idempotency_key = null,
    updated_at = now()
from ranked
where request.id = ranked.id and ranked.row_number > 1;

drop index if exists public.idx_replenishment_idempotency;
drop index if exists public.idx_replenishment_requests_idempotency;
drop index if exists public.uq_replenishment_idempotency;
drop index if exists public.uq_replenishment_requests_idempotency;
drop index if exists public.wms_replenishment_idempotency_uidx;

create unique index if not exists wms_replenishment_idempotency_uidx
  on public.wms_replenishment_requests (warehouse_code, idempotency_key)
  where idempotency_key is not null and idempotency_key <> '';
create index if not exists wms_replenishment_status_updated_idx
  on public.wms_replenishment_requests (warehouse_code, status, updated_at desc);
create index if not exists wms_replenishment_material_status_idx
  on public.wms_replenishment_requests (warehouse_code, codigo_material, status);
create index if not exists wms_replenishment_responsible_status_idx
  on public.wms_replenishment_requests (warehouse_code, responsavel_id, status);

-- Keep one active stock-position row per exact warehouse/source/material/address.
with ranked as (
  select id, warehouse_code, source_type, codigo_material, codigo_endereco,
         row_number() over (
           partition by warehouse_code, source_type, codigo_material, coalesce(codigo_endereco, '')
           order by created_at, id
         ) as row_number
  from public.wms_stock_positions
  where active is true
)
insert into public.wms_migration_audit (migration_name, table_name, record_id, action, previous_value, notes)
select '20260924014042_operational_data_integrity', 'wms_stock_positions', id, 'DEACTIVATE_DUPLICATE_POSITION',
       jsonb_build_object('warehouse_code', warehouse_code, 'source_type', source_type, 'codigo_material', codigo_material, 'codigo_endereco', codigo_endereco),
       'Duplicate row retained for audit and marked inactive.'
from ranked
where row_number > 1
  and not exists (
    select 1 from public.wms_migration_audit audit
    where audit.migration_name = '20260924014042_operational_data_integrity'
      and audit.table_name = 'wms_stock_positions'
      and audit.record_id = ranked.id
      and audit.action = 'DEACTIVATE_DUPLICATE_POSITION'
  );

with ranked as (
  select id,
         row_number() over (
           partition by warehouse_code, source_type, codigo_material, coalesce(codigo_endereco, '')
           order by created_at, id
         ) as row_number
  from public.wms_stock_positions
  where active is true
)
update public.wms_stock_positions position
set active = false,
    updated_at = now()
from ranked
where position.id = ranked.id and ranked.row_number > 1;

create unique index if not exists wms_stock_positions_active_location_uidx
  on public.wms_stock_positions (warehouse_code, source_type, codigo_material, coalesce(codigo_endereco, ''))
  where active is true;

-- Normalize every warehouse-aware table without removing the legacy warehouse row.
do $$
declare
  table_row record;
begin
  for table_row in
    select distinct table_name
    from information_schema.columns
    where table_schema = 'public'
      and column_name = 'warehouse_code'
      and table_name like 'wms_%'
  loop
    execute format(
      'update public.%I set warehouse_code = ''VDAR'' where upper(coalesce(warehouse_code, '''')) in (''VDR'', ''DVR'')',
      table_row.table_name
    );
  end loop;

  for table_row in
    select distinct table_name
    from information_schema.columns
    where table_schema = 'public'
      and column_name = 'warehouse_id'
      and table_name like 'wms_%'
  loop
    execute format(
      'update public.%I set warehouse_id = ''warehouse-vdar'' where lower(coalesce(warehouse_id, '''')) in (''warehouse-vdr'', ''warehouse-dvr'')',
      table_row.table_name
    );
  end loop;
end
$$;

update public.wms_users
set allowed_warehouse_codes = replace(replace(coalesce(allowed_warehouse_codes, ''), 'VDR', 'VDAR'), 'DVR', 'VDAR'),
    default_warehouse_code = case when upper(coalesce(default_warehouse_code, '')) in ('VDR','DVR') then 'VDAR' else default_warehouse_code end,
    default_warehouse_id = case when lower(coalesce(default_warehouse_id, '')) in ('warehouse-vdr','warehouse-dvr') then 'warehouse-vdar' else default_warehouse_id end,
    updated_at = now()
where allowed_warehouse_codes like '%VDR%'
   or allowed_warehouse_codes like '%DVR%'
   or upper(coalesce(default_warehouse_code, '')) in ('VDR','DVR')
   or lower(coalesce(default_warehouse_id, '')) in ('warehouse-vdr','warehouse-dvr');

update public.wms_warehouses
set active = false,
    notes = concat_ws(' | ', nullif(notes, ''), 'Legacy alias migrated to VDAR; row preserved for audit.'),
    updated_at = now()
where upper(code) in ('VDR','DVR');

create or replace function public.wms_replenishment_schema_diagnostics()
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not private.current_wms_is_global_admin() then
    raise exception 'insufficient_privilege' using errcode = '42501';
  end if;
  select jsonb_build_object(
    'table_exists', to_regclass('public.wms_replenishment_requests') is not null,
    'columns', coalesce((select jsonb_agg(column_name order by ordinal_position) from information_schema.columns where table_schema = 'public' and table_name = 'wms_replenishment_requests'), '[]'::jsonb),
    'indexes', coalesce((select jsonb_agg(indexname order by indexname) from pg_indexes where schemaname = 'public' and tablename = 'wms_replenishment_requests'), '[]'::jsonb),
    'rls_enabled', coalesce((select relrowsecurity from pg_class where oid = to_regclass('public.wms_replenishment_requests')), false),
    'checked_at', now()
  ) into result;
  return result;
end
$$;

revoke all on function public.wms_replenishment_schema_diagnostics() from public, anon;
grant execute on function public.wms_replenishment_schema_diagnostics() to authenticated;

insert into public.wms_schema_version (id, version, description, applied_at, applied_by)
values ('current', '2026.09.23.003', 'Operational deduplication, canonical indexes and VDAR normalization', now(), 'security-hardening')
on conflict (id) do update
set version = excluded.version,
    description = excluded.description,
    applied_at = excluded.applied_at,
    applied_by = excluded.applied_by;
